/**
 * Auto-generated migration map for security-dashboard
 * Maps old API function names to generated @autional-cn/shared/generated/api
 * Generated by: python scripts/generate_api_ts.py --migration security-dashboard
 */
import * as Generated from '@autional-cn/shared/generated/api';

export const getAuditLogs = Generated.adminAuditLogs;
export const getAuditLogDetail = Generated.adminAuditLogsByLogs;
export const getAuditStats = Generated.adminAuditStats;
export const verifyAuditChain = Generated.adminAuditVerificationsPost;
export const getVerificationResults = Generated.adminAuditVerifications;
export const getHashChain = Generated.adminAuditHashchainByHashchain;
export const getArchiveStatus = Generated.adminAuditArchiveStatus;
export const exportAuditLogs = Generated.adminAuditExportPost;
export const getAnomalies = Generated.adminAuditAnomalies;
export const updateAnomalyStatus = Generated.adminAuditAnomaliesStatusByAnomaliesPut;
export const getAnomalyById = Generated.adminAuditAnomaliesByAnomalies;
export const getAnomalyTimeline = Generated.adminAuditAnomaliesTimelineByAnomalies;
export const getRelatedAnomalies = Generated.adminAuditAnomaliesRelatedByAnomalies;
export const assignAnomaly = Generated.adminAuditAnomaliesAssignByAnomaliesPost;
export const addAnomalyComment = Generated.adminAuditAnomaliesCommentByAnomaliesPost;
export const getComplianceStatus = Generated.complianceStatus;
export const getDSARs = Generated.adminComplianceGdprDsar;
export const getDSARById = Generated.adminComplianceGdprDsarByDsar;
export const getDSARStatus = Generated.complianceGdprDsarStatusByDsar;
export const updateDSAR = Generated.adminComplianceGdprDsarByDsarPut;
export const getBreachNotifications = Generated.adminComplianceBreachNotifications;
export const updateBreachNotification =
	Generated.adminComplianceBreachNotificationsByBreachNotificationsPut;
export const getEvidence = Generated.adminComplianceEvidence;
export const getEvidenceById = Generated.adminComplianceEvidenceByEvidence;
export const getRetentionPolicies = Generated.adminComplianceRetentionPolicies;
export const getISOControls = Generated.adminComplianceIso27001Controls;
export const getSOXControls = Generated.adminComplianceSoxItgc;
export const getPenTestReports = Generated.adminCompliancePenetrationTestReports;
export const getAuditFindings = Generated.adminComplianceAuditFindings;
export const getAuditFindingById = Generated.adminComplianceAuditFindingsByAuditFindings;
export const updateAuditFinding = Generated.adminComplianceAuditFindingsByAuditFindingsPut;
export const getSessions = Generated.sessions;
export const getActiveSessionCount = Generated.adminSessionsActiveCount;
export const terminateSession = Generated.sessionsBySessionsDelete;
export const getSecurityReport = Generated.adminAuditReportsSecurity;
export const getComplianceReport = Generated.adminAuditReportsCompliance;
export const getExportJobs = Generated.adminAuditExportJobs;
export const getExportStatus = Generated.adminAuditExportStatusByExport;
export const downloadExport = Generated.adminAuditExportDownloadByExport;
export const createExportJob = Generated.adminAuditExportPost;
export const getMerkleRoot = Generated.adminAuditMerkleRoot;
export const getMerkleProof = Generated.adminAuditMerkleProof;
export const getRetentionPolicy = Generated.adminAuditRetentionPolicy;
export const updateRetentionPolicyAdmin = Generated.adminAuditRetentionPolicyPut;
export const getSiemConnectors = Generated.adminAuditSiemConnectors;
export const createSiemConnector = Generated.adminAuditSiemConnectorsPost;
export const updateSiemConnector = Generated.adminAuditSiemConnectorsByConnectorsPut;
export const deleteSiemConnector = Generated.adminAuditSiemConnectorsByConnectorsDelete;
export const testSiemConnector = Generated.adminAuditSiemConnectorsTestByConnectorsPost;
export const triggerArchive = Generated.adminAuditArchivePost;
export const getAlerts = Generated.adminAuditAlerts;
export const getAlertById = Generated.adminAuditAlertsByAlerts;
export const assignAlert = Generated.adminAuditAlertsAssignByAlertsPost;
export const updateAlertStatus = Generated.adminAuditAlertsStatusByAlertsPut;
// @generated-api-exempt: BFF gateway composite endpoints — registered at
// /bff/gateway/api/v1/security on gateway engine (JWT required). apiClient
// prepends /bff, so use raw fetch with the Bearer token (same pattern as
// SSEEventStream) to reach /bff/gateway/api/v1/security/users.
// Response keys are snake_case (raw fetch bypasses apiClient interceptor), so apply
// camelCaseKeys to match the interceptor behavior expected by the pages.
export const getSecurityUserProfile = async (userId: string) => {
	const token = (await import('@autional-cn/shared')).getAccessToken();
	const { camelCaseKeys } = await import('@autional-cn/shared');
	const res = await fetch(`/bff/gateway/api/v1/security/users/${userId}/profile`, {
		headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' },
	});
	if (!res.ok) throw new Error(`HTTP ${res.status}`);
	const body = await res.json();
	return camelCaseKeys(body.data);
};
// @generated-api-exempt: BFF gateway composite endpoints — registered at
// /bff/gateway/api/v1/security on gateway engine (JWT required)
export const getSecurityUserTimeline = async (userId: string) => {
	const token = (await import('@autional-cn/shared')).getAccessToken();
	const { camelCaseKeys } = await import('@autional-cn/shared');
	const res = await fetch(`/bff/gateway/api/v1/security/users/${userId}/timeline`, {
		headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' },
	});
	if (!res.ok) throw new Error(`HTTP ${res.status}`);
	const body = await res.json();
	return camelCaseKeys(body.data);
};
export const getNotificationPlatformStats = Generated.adminNotificationsPlatformStats;
export const getNotificationReadReport = Generated.notificationsReadReport;
export const getCommunicationPlatformStats = Generated.adminCommunicationPlatformStats;
export const getAdminAgents = Generated.adminAgents;
export const getAdminRobots = Generated.adminRobots;
export const getAdminIots = Generated.adminIots;

// Agent mutations
export const createAgent = Generated.adminAgentsPost;
export const getAgentById = Generated.adminAgentsByAgents;
export const updateAgent = Generated.adminAgentsByAgentsPut;
export const deleteAgent = Generated.adminAgentsByAgentsDelete;

// Robot mutations
export const createRobot = Generated.adminRobotsPost;
export const getRobotById = Generated.adminRobotsByRobots;
export const updateRobot = Generated.adminRobotsByRobotsPut;
export const deleteRobot = Generated.adminRobotsByRobotsDelete;
export const commissionRobot = Generated.adminRobotsCommissionByRobotsPost;
export const decommissionRobot = Generated.adminRobotsDecommissionByRobotsPost;
export const issueIntentToken = Generated.adminRobotsIntentByRobotsPost;
export const revokeIntentToken = Generated.adminRobotsIntentRevokeByRobotsPost;

// Device mutations
export const createDevice = Generated.adminIotsPost;
export const getDeviceById = Generated.adminIotsByIots;
export const deleteDevice = Generated.adminIotsByIotsDelete;
export const pairDevice = Generated.iotsPairPost;
export const unpairDevice = Generated.iotsByIotsDelete;
export const transferDevice = Generated.iotsTransferByIotsPost;

// NHI Policy
export const getNhiPolicy = Generated.adminPoliciesNhi;
export const updateNhiPolicy = Generated.adminPoliciesNhiPut;
export const fetchGatewayStatusRaw = async () => {
	const res = await fetch('/ready');
	return res.json();
};
